FROM node:10

# create app directory
WORKDIR /usr/src/room

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

COPY .env.docker ./.env

RUN ls

RUN npm install


EXPOSE 3000
EXPOSE 35729

COPY ./shared ./shared

COPY ./src ./src

COPY ./public ./public

RUN ls

# run server
CMD [ "npm", "run", "develop:frontend" ]